-- ========================================
-- FILE 1: SETUP V?I SYS AS SYSDBA
-- ========================================
-- Ch?y file này v?i user: SYS AS SYSDBA
-- Sau ?ó ch?y 3 file ti?p theo v?i CAFEAPP
-- ========================================

SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT ========================================
PROMPT FILE 1: SETUP VOI SYS AS SYSDBA
PROMPT ========================================
PROMPT 
PROMPT Buoc nay se:
PROMPT 1. Tao user C##CAFE_APP
PROMPT 2. Grant cac quyen can thiet
PROMPT 3. Tao profile (neu can)
PROMPT 4. Cap quyen cho VPD, FGA
PROMPT 
PROMPT ========================================

PROMPT Buoc 1: Xoa user cu (neu co)...
BEGIN
    EXECUTE IMMEDIATE 'DROP USER C##CAFE_APP CASCADE';
    DBMS_OUTPUT.PUT_LINE(' Da xoa user C##CAFE_APP cu');
EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('* User C##CAFE_APP chua ton tai');
END;
/

PROMPT Buoc 2: Tao user moi...
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER CAFEAPP IDENTIFIED BY "Cafe@123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

PROMPT Buoc 3: Grant quyen co ban...
GRANT CONNECT, RESOURCE TO C##CAFE_APP;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE VIEW TO C##CAFE_APP;
GRANT CREATE SEQUENCE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO C##CAFE_APP;

PROMPT Buoc 4: Grant quyen cho ma hoa va bao mat...
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO C##CAFE_APP;
GRANT EXECUTE ON SYS.DBMS_SESSION TO C##CAFE_APP;
GRANT EXECUTE ON SYS.DBMS_FGA TO C##CAFE_APP;
GRANT EXECUTE ON SYS.DBMS_RLS TO C##CAFE_APP;
GRANT EXECUTE ON SYS.DBMS_OUTPUT TO C##CAFE_APP;
GRANT EXECUTE ON SYS.DBMS_RANDOM TO C##CAFE_APP;
GRANT EXECUTE ON SYS.DBMS_LOB TO C##CAFE_APP;
GRANT CREATE ANY CONTEXT TO C##CAFE_APP;
GRANT DROP ANY CONTEXT TO C##CAFE_APP;
GRANT AUDIT ANY TO C##CAFE_APP;

-- Thêm quy?n c?n thi?t cho VPD
GRANT EXECUTE ON SYS.DBMS_RLS TO C##CAFE_APP WITH GRANT OPTION;
GRANT CREATE JOB TO C##CAFE_APP;
GRANT CREATE ANY DIRECTORY TO C##CAFE_APP;

PROMPT Buoc 5: Tao profile (mo phong)...
BEGIN
  -- Xoa profile cu neu co
  BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE CAFE_ADMIN_PROFILE CASCADE';
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  
  BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE CAFE_STAFF_PROFILE CASCADE';
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  
  -- Tao profile moi
  EXECUTE IMMEDIATE 'CREATE PROFILE CAFE_ADMIN_PROFILE LIMIT
    SESSIONS_PER_USER 5
    IDLE_TIME 60
    CONNECT_TIME 480
    PASSWORD_LIFE_TIME 90
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 1/24
    PASSWORD_REUSE_TIME 30
    PASSWORD_REUSE_MAX 3';
    
  EXECUTE IMMEDIATE 'CREATE PROFILE CAFE_STAFF_PROFILE LIMIT
    SESSIONS_PER_USER 3
    IDLE_TIME 30
    CONNECT_TIME 240
    PASSWORD_LIFE_TIME 60
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1/24
    PASSWORD_REUSE_TIME 15
    PASSWORD_REUSE_MAX 5';
    
  DBMS_OUTPUT.PUT_LINE(' Da tao 2 profile: CAFE_ADMIN_PROFILE va CAFE_STAFF_PROFILE');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(' Khong the tao profile (co the do quyen): ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE(' He thong van hoat dong binh thuong, chi khong co profile');
END;
/

PROMPT Buoc 6: Gan profile cho user (neu da tao duoc)...
BEGIN
  EXECUTE IMMEDIATE 'ALTER USER C##CAFE_APP PROFILE CAFE_ADMIN_PROFILE';
  DBMS_OUTPUT.PUT_LINE(' Da gan profile CAFE_ADMIN_PROFILE cho user C##CAFE_APP');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(' Khong the gan profile (bo qua)');
END;
/

PROMPT Buoc 7: Tao tablespace cho du lieu nhay cam...
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLESPACE SECURE_DATA
    DATAFILE ''secure_data01.dbf''
    SIZE 100M
    AUTOEXTEND ON
    NEXT 10M
    MAXSIZE 500M';
    
  EXECUTE IMMEDIATE 'ALTER USER C##CAFE_APP QUOTA UNLIMITED ON SECURE_DATA';
  DBMS_OUTPUT.PUT_LINE(' Da tao tablespace SECURE_DATA');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(' Khong the tao tablespace: ' || SQLERRM);
END;
/

PROMPT ========================================
PROMPT HOAN THANH FILE 1!
PROMPT 
PROMPT TIEP THEO:
PROMPT 1. Ket noi voi user C##CAFE_APP/Cafe@123
PROMPT 2. Chay file 01_SETUP_CORE.sql
PROMPT ========================================

-- Kiem tra
SELECT 'User C##CAFE_APP da duoc tao' AS STATUS FROM DUAL
WHERE EXISTS (SELECT 1 FROM DBA_USERS WHERE USERNAME = 'C##CAFE_APP');

SELECT 'Profile da tao' AS STATUS FROM DUAL
WHERE EXISTS (SELECT 1 FROM DBA_PROFILES WHERE PROFILE = 'CAFE_ADMIN_PROFILE');