-- ========================================
-- FILE 2: SETUP CORE H? TH?NG
-- ========================================
-- Ch?y file này v?i user: CAFEAPP/Cafe@123
-- Sau khi ?ã ch?y file 00_SETUP_SYS.sql v?i SYS
-- ========================================

SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT ========================================
PROMPT FILE 2: SETUP CORE HE THONG
PROMPT ========================================
PROMPT 
PROMPT Buoc nay se:
PROMPT 1. Tao bang va sequence (THEM FGA_LOG)
PROMPT 2. Tao package co ban
PROMPT 3. Tao procedure va function
PROMPT 4. Tao view
PROMPT 5. Them du lieu mau
PROMPT 
PROMPT ========================================

PROMPT *** BUOC 1: TAO SEQUENCE ***
-- Xoa sequence cu neu co
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_nhanvien';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_khachhang';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_ban';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_hoadon';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_phieunhap';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_mon';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_nguyenlieu';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_nhacungcap';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Tao sequence moi
CREATE SEQUENCE seq_nhanvien START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_khachhang START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_ban START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_hoadon START WITH 10001 INCREMENT BY 1;
CREATE SEQUENCE seq_phieunhap START WITH 50001 INCREMENT BY 1;
CREATE SEQUENCE seq_mon START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_nguyenlieu START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_nhacungcap START WITH 1 INCREMENT BY 1;

PROMPT  Da tao 8 sequence

PROMPT *** BUOC 2: TAO BANG (DA SUA LOI KHOAS NGOAI) ***

-- Bang phan quyen
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PHANQUYEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE PHANQUYEN (
  ROLE_CODE VARCHAR2(30) PRIMARY KEY,
  MOTA VARCHAR2(200)
);

-- Bang nhan vien
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE NHANVIEN (
  MANV NUMBER PRIMARY KEY,
  HOTEN VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL UNIQUE,
  SODT VARCHAR2(15),
  NGAYSINH DATE,
  TRANGTHAI VARCHAR2(20) DEFAULT 'ACTIVE',
  NGAYTAO DATE DEFAULT SYSDATE
);

-- Bang tai khoan (DA THEM ON DELETE CASCADE)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TAIKHOAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE TAIKHOAN (
  USERNAME VARCHAR2(50) PRIMARY KEY,
  MANV NUMBER NOT NULL,
  PASSWORD_HASH RAW(2000) NOT NULL,
  SALT RAW(64) NOT NULL,
  ROLE_CODE VARCHAR2(30) NOT NULL,
  LOGIN_FAILS NUMBER DEFAULT 0,
  LOCKED_UNTIL DATE,
  LAST_LOGIN_AT DATE,
  PASSWORD_CHANGED_AT DATE DEFAULT SYSDATE, -- M?I
  PASSWORD_EXPIRES_AT DATE DEFAULT SYSDATE + 90, -- M?I
  CREATED_AT DATE DEFAULT SYSDATE,
  CONSTRAINT fk_tk_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE,
  CONSTRAINT fk_tk_role FOREIGN KEY (ROLE_CODE) REFERENCES PHANQUYEN(ROLE_CODE)
);

-- Bang lich su dang nhap
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LICHSU_DANGNHAP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE LICHSU_DANGNHAP (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR2(50),
  MANV NUMBER,
  HOATDONG VARCHAR2(50),
  THOIGIAN DATE DEFAULT SYSDATE,
  IP_ADDRESS VARCHAR2(50),
  GHI_CHU VARCHAR2(500),
  CONSTRAINT fk_ls_user FOREIGN KEY (USERNAME) REFERENCES TAIKHOAN(USERNAME),
  CONSTRAINT fk_ls_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bang ban
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE BAN (
  MABAN NUMBER PRIMARY KEY,
  TENBAN VARCHAR2(50) NOT NULL,
  VITRI VARCHAR2(100),
  TRANGTHAI VARCHAR2(20) DEFAULT 'TRONG'
);

-- Bang khach hang
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE KHACHHANG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE KHACHHANG (
  MAKH NUMBER PRIMARY KEY,
  HOTEN VARCHAR2(100) NOT NULL,
  SODT VARCHAR2(15),
  EMAIL VARCHAR2(100),
  LOAIKH VARCHAR2(20) DEFAULT 'LE'
);

-- Bang mon
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MON CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE MON (
  MAMON NUMBER PRIMARY KEY,
  TENMON VARCHAR2(100) NOT NULL,
  LOAIMON VARCHAR2(50),
  DONGIA NUMBER NOT NULL,
  TRANGTHAI VARCHAR2(20) DEFAULT 'BAN'
);

-- Bang hoa don
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE HOADON CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE HOADON (
  MAHD NUMBER PRIMARY KEY,
  MANV NUMBER NOT NULL,
  MABAN NUMBER NOT NULL,
  MAKH NUMBER,
  NGAYLAP DATE DEFAULT SYSDATE,
  TONGTIEN NUMBER DEFAULT 0,
  TRANGTHAI VARCHAR2(20) DEFAULT 'CHO',
  CONSTRAINT fk_hd_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
  CONSTRAINT fk_hd_ban FOREIGN KEY (MABAN) REFERENCES BAN(MABAN),
  CONSTRAINT fk_hd_kh FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- Bang chi tiet hoa don
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CHITIET_HD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE CHITIET_HD (
  MAHD NUMBER NOT NULL,
  MAMON NUMBER NOT NULL,
  SOLUONG NUMBER NOT NULL,
  DONGIA NUMBER NOT NULL,
  GIAMGIA NUMBER DEFAULT 0,
  THANHTIEN NUMBER,
  PRIMARY KEY (MAHD, MAMON),
  CONSTRAINT fk_cthd_hd FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD) ON DELETE CASCADE,
  CONSTRAINT fk_cthd_mon FOREIGN KEY (MAMON) REFERENCES MON(MAMON)
);

-- Bang nha cung cap
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE NHACUNGCAP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE NHACUNGCAP (
  MANCC NUMBER PRIMARY KEY,
  TENNCC VARCHAR2(200) NOT NULL,
  SODT VARCHAR2(15),
  EMAIL VARCHAR2(100),
  DIACHI VARCHAR2(500)
);

-- Bang nguyen lieu
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE NGUYENLIEU CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE NGUYENLIEU (
  MANL NUMBER PRIMARY KEY,
  TENNL VARCHAR2(100) NOT NULL,
  DONVI VARCHAR2(20),
  SOLUONGTON NUMBER DEFAULT 0,
  SECURITY_LEVEL VARCHAR2(20) DEFAULT 'PUBLIC',
  MANCC_CHINH NUMBER,
  CONSTRAINT fk_nl_ncc FOREIGN KEY (MANCC_CHINH) REFERENCES NHACUNGCAP(MANCC)
);

-- Bang phieu nhap
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PHIEUNHAP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE PHIEUNHAP (
  MAPN NUMBER PRIMARY KEY,
  MANCC NUMBER NOT NULL,
  MANV NUMBER NOT NULL,
  NGAYNHAP DATE DEFAULT SYSDATE,
  TONGTIEN NUMBER DEFAULT 0,
  CONSTRAINT fk_pn_ncc FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
  CONSTRAINT fk_pn_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bang chi tiet phieu nhap
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CHITIET_PN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE CHITIET_PN (
  MAPN NUMBER NOT NULL,
  MANL NUMBER NOT NULL,
  SOLUONG NUMBER NOT NULL,
  DONGIA NUMBER NOT NULL,
  THANHTIEN NUMBER,
  PRIMARY KEY (MAPN, MANL),
  CONSTRAINT fk_ctpn_pn FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN) ON DELETE CASCADE,
  CONSTRAINT fk_ctpn_nl FOREIGN KEY (MANL) REFERENCES NGUYENLIEU(MANL)
);

-- Bang audit log
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE AUDIT_LOG (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR2(50),
  ACTION_TYPE VARCHAR2(50),
  TABLE_NAME VARCHAR2(50),
  RECORD_ID VARCHAR2(100),
  OLD_VALUE CLOB,
  NEW_VALUE CLOB,
  ACTION_TIME DATE DEFAULT SYSDATE,
  IP_ADDRESS VARCHAR2(50)
);

-- Bang FGA_LOG (M?I - ?Ã THÊM)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FGA_LOG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE FGA_LOG (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR2(100),
  TABLE_NAME VARCHAR2(50),
  POLICY_NAME VARCHAR2(100),
  SQL_TEXT CLOB,
  TIMESTAMP DATE DEFAULT SYSDATE,
  CLIENT_IP VARCHAR2(50)
);

-- Bang cau hinh
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE APP_CONFIG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE APP_CONFIG (
  CONFIG_KEY VARCHAR2(100) PRIMARY KEY,
  CONFIG_VAL RAW(2000)
);

-- Bang du lieu nha?y ca?m tren tablespace riêng (M?I)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SENSITIVE_DATA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE SENSITIVE_DATA (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATA_TYPE VARCHAR2(50),
  ENCRYPTED_DATA RAW(2000),
  IV RAW(16),
  CREATED_AT DATE DEFAULT SYSDATE,
  CREATED_BY VARCHAR2(100)
) TABLESPACE SECURE_DATA; -- DÙNG TABLESPACE RIÊNG

-- Them rang buoc CHECK
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NHANVIEN ADD CONSTRAINT chk_nv_trangthai CHECK (TRANGTHAI IN (''ACTIVE'', ''INACTIVE''))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BAN ADD CONSTRAINT chk_ban_trangthai CHECK (TRANGTHAI IN (''TRONG'', ''DANG_SU_DUNG'', ''BAO_TRI''))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD CONSTRAINT chk_hd_trangthai CHECK (TRANGTHAI IN (''CHO'', ''DA_THANH_TOAN'', ''HUY''))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE MON ADD CONSTRAINT chk_mon_trangthai CHECK (TRANGTHAI IN (''BAN'', ''NGUNG_BAN''))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE KHACHHANG ADD CONSTRAINT chk_kh_loai CHECK (LOAIKH IN (''LE'', ''THUONG'', ''VIP''))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NGUYENLIEU ADD CONSTRAINT chk_nl_security CHECK (SECURITY_LEVEL IN (''PUBLIC'', ''INTERNAL'', ''CONFIDENTIAL''))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_tk_password CHECK (LENGTH(RAWTOHEX(PASSWORD_HASH)) = 64)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Tao index
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_hoadon_ngaylap ON HOADON(NGAYLAP)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cthd_mahd ON CHITIET_HD(MAHD)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_taikhoan_manv ON TAIKHOAN(MANV)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_lichsu_username ON LICHSU_DANGNHAP(USERNAME)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_hoadon_trangthai ON HOADON(TRANGTHAI)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_mon_loaimon ON MON(LOAIMON)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_nl_security ON NGUYENLIEU(SECURITY_LEVEL)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_fga_username ON FGA_LOG(USERNAME)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT  Da tao 14 bang va index

PROMPT *** BUOC 3: TAO PACKAGE CO BAN ***

-- PACKAGE MA HOA
BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_crypto';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE PACKAGE pkg_crypto AS
  FUNCTION gen_random_raw(p_length NUMBER) RETURN RAW;
  FUNCTION aes_encrypt(p_text VARCHAR2, p_key RAW, p_iv RAW) RETURN RAW;
  FUNCTION aes_decrypt(p_encrypted RAW, p_key RAW, p_iv RAW) RETURN VARCHAR2;
  FUNCTION hash_password(p_password VARCHAR2, p_salt RAW) RETURN RAW;
  FUNCTION check_password_strength(p_password VARCHAR2) RETURN VARCHAR2;
END pkg_crypto;
/

CREATE OR REPLACE PACKAGE BODY pkg_crypto AS
  FUNCTION gen_random_raw(p_length NUMBER) RETURN RAW IS
    v_random RAW(2000);
  BEGIN
    v_random := SYS.DBMS_CRYPTO.RANDOMBYTES(p_length);
    RETURN v_random;
  END;

  FUNCTION aes_encrypt(p_text VARCHAR2, p_key RAW, p_iv RAW) RETURN RAW IS
  BEGIN
    RETURN SYS.DBMS_CRYPTO.ENCRYPT(
      UTL_RAW.CAST_TO_RAW(p_text),
      SYS.DBMS_CRYPTO.ENCRYPT_AES256 + SYS.DBMS_CRYPTO.CHAIN_CBC + SYS.DBMS_CRYPTO.PAD_PKCS5,
      p_key, p_iv
    );
  END;

  FUNCTION aes_decrypt(p_encrypted RAW, p_key RAW, p_iv RAW) RETURN VARCHAR2 IS
  BEGIN
    RETURN UTL_RAW.CAST_TO_VARCHAR2(
      SYS.DBMS_CRYPTO.DECRYPT(
        p_encrypted,
        SYS.DBMS_CRYPTO.ENCRYPT_AES256 + SYS.DBMS_CRYPTO.CHAIN_CBC + SYS.DBMS_CRYPTO.PAD_PKCS5,
        p_key, p_iv
      )
    );
  END;
  
  FUNCTION hash_password(p_password VARCHAR2, p_salt RAW) RETURN RAW IS
  BEGIN
    RETURN SYS.DBMS_CRYPTO.HASH(
      UTL_RAW.CAST_TO_RAW(p_password || RAWTOHEX(p_salt)),
      SYS.DBMS_CRYPTO.HASH_SH256
    );
  END;
  
  FUNCTION check_password_strength(p_password VARCHAR2) RETURN VARCHAR2 IS
    v_score NUMBER := 0;
  BEGIN
    -- Ki?m tra ?? dài
    IF LENGTH(p_password) >= 8 THEN v_score := v_score + 1; END IF;
    
    -- Có ch? hoa
    IF REGEXP_LIKE(p_password, '[A-Z]') THEN v_score := v_score + 1; END IF;
    
    -- Có ch? th??ng
    IF REGEXP_LIKE(p_password, '[a-z]') THEN v_score := v_score + 1; END IF;
    
    -- Có s?
    IF REGEXP_LIKE(p_password, '[0-9]') THEN v_score := v_score + 1; END IF;
    
    -- Có ký t? ??c bi?t
    IF REGEXP_LIKE(p_password, '[^A-Za-z0-9]') THEN v_score := v_score + 1; END IF;
    
    -- ?ánh giá
    IF v_score >= 4 THEN
      RETURN 'STRONG';
    ELSIF v_score >= 3 THEN
      RETURN 'MEDIUM';
    ELSE
      RETURN 'WEAK';
    END IF;
  END;
END pkg_crypto;
/

-- PACKAGE HOA DON
BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_hoadon';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE PACKAGE pkg_hoadon AS
  FUNCTION tao_hoadon(p_manv IN NUMBER, p_maban IN NUMBER, p_makh IN NUMBER) RETURN NUMBER;
  PROCEDURE them_cthd(p_mahd NUMBER, p_mamon NUMBER, p_soluong NUMBER, p_dongia NUMBER, p_giamgia NUMBER := 0);
  PROCEDURE cap_nhat_tongtien(p_mahd NUMBER);
  PROCEDURE thanh_toan(p_mahd NUMBER);
  FUNCTION generate_hoadon_report(p_from_date DATE, p_to_date DATE) RETURN SYS_REFCURSOR;
END pkg_hoadon;
/

CREATE OR REPLACE PACKAGE BODY pkg_hoadon AS
  FUNCTION tao_hoadon(
    p_manv IN NUMBER, 
    p_maban IN NUMBER, 
    p_makh IN NUMBER
  ) RETURN NUMBER IS
    v_mahd NUMBER;
  BEGIN
    v_mahd := seq_hoadon.NEXTVAL;
    INSERT INTO HOADON(MAHD, MANV, MABAN, MAKH, NGAYLAP, TONGTIEN, TRANGTHAI)
    VALUES (v_mahd, p_manv, p_maban, p_makh, SYSDATE, 0, 'CHO');
    UPDATE BAN SET TRANGTHAI = 'DANG_SU_DUNG' WHERE MABAN = p_maban;
    COMMIT;
    RETURN v_mahd;
  END;

  PROCEDURE them_cthd(p_mahd NUMBER, p_mamon NUMBER, p_soluong NUMBER, p_dongia NUMBER, p_giamgia NUMBER := 0) IS
    v_thanhtien NUMBER;
  BEGIN
    v_thanhtien := (p_soluong * p_dongia) - p_giamgia;
    INSERT INTO CHITIET_HD(MAHD, MAMON, SOLUONG, DONGIA, GIAMGIA, THANHTIEN)
    VALUES (p_mahd, p_mamon, p_soluong, p_dongia, p_giamgia, v_thanhtien);
    COMMIT;
  END;

  PROCEDURE cap_nhat_tongtien(p_mahd NUMBER) IS
    v_tong NUMBER;
  BEGIN
    SELECT SUM(THANHTIEN) INTO v_tong FROM CHITIET_HD WHERE MAHD = p_mahd;
    UPDATE HOADON SET TONGTIEN = NVL(v_tong, 0) WHERE MAHD = p_mahd;
    COMMIT;
  END;

  PROCEDURE thanh_toan(p_mahd NUMBER) IS
    v_maban NUMBER;
  BEGIN
    SELECT MABAN INTO v_maban FROM HOADON WHERE MAHD = p_mahd;
    UPDATE HOADON SET TRANGTHAI = 'DA_THANH_TOAN' WHERE MAHD = p_mahd;
    UPDATE BAN SET TRANGTHAI = 'TRONG' WHERE MABAN = v_maban;
    COMMIT;
  END;
  
  FUNCTION generate_hoadon_report(p_from_date DATE, p_to_date DATE) RETURN SYS_REFCURSOR IS
    v_cursor SYS_REFCURSOR;
  BEGIN
    OPEN v_cursor FOR
    SELECT 
      MAHD,
      MANV,
      MABAN,
      MAKH,
      NGAYLAP,
      TONGTIEN,
      TRANGTHAI
    FROM HOADON
    WHERE NGAYLAP BETWEEN p_from_date AND p_to_date
    ORDER BY NGAYLAP DESC;
    
    RETURN v_cursor;
  END;
END pkg_hoadon;
/

-- PACKAGE NHAP HANG
BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_nhaphang';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE OR REPLACE PACKAGE pkg_nhaphang AS
  FUNCTION tao_phieunhap(p_mancc NUMBER, p_manv NUMBER) RETURN NUMBER;
  PROCEDURE them_ctpn(p_mapn NUMBER, p_manl NUMBER, p_soluong NUMBER, p_dongia NUMBER);
  PROCEDURE cap_nhat_tongtien(p_mapn NUMBER);
  PROCEDURE hoan_tat_nhap(p_mapn NUMBER);
  FUNCTION check_inventory(p_manl NUMBER) RETURN NUMBER;
END pkg_nhaphang;
/

CREATE OR REPLACE PACKAGE BODY pkg_nhaphang AS
  FUNCTION tao_phieunhap(p_mancc NUMBER, p_manv NUMBER) RETURN NUMBER IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_mapn NUMBER;
  BEGIN
    v_mapn := seq_phieunhap.NEXTVAL;
    INSERT INTO PHIEUNHAP(MAPN, MANCC, MANV, NGAYNHAP, TONGTIEN)
    VALUES (v_mapn, p_mancc, p_manv, SYSDATE, 0);
    COMMIT;
    RETURN v_mapn;
  END;

  PROCEDURE them_ctpn(p_mapn NUMBER, p_manl NUMBER, p_soluong NUMBER, p_dongia NUMBER) IS
    v_thanhtien NUMBER;
  BEGIN
    v_thanhtien := p_soluong * p_dongia;
    INSERT INTO CHITIET_PN(MAPN, MANL, SOLUONG, DONGIA, THANHTIEN)
    VALUES (p_mapn, p_manl, p_soluong, p_dongia, v_thanhtien);
    COMMIT;
  END;

  PROCEDURE cap_nhat_tongtien(p_mapn NUMBER) IS
    v_tong NUMBER;
  BEGIN
    SELECT NVL(SUM(THANHTIEN), 0) INTO v_tong FROM CHITIET_PN WHERE MAPN = p_mapn;
    UPDATE PHIEUNHAP SET TONGTIEN = v_tong WHERE MAPN = p_mapn;
    COMMIT;
  END;

  PROCEDURE hoan_tat_nhap(p_mapn NUMBER) IS
  BEGIN
    FOR rec IN (SELECT MANL, SOLUONG FROM CHITIET_PN WHERE MAPN = p_mapn) LOOP
      UPDATE NGUYENLIEU SET SOLUONGTON = SOLUONGTON + rec.SOLUONG WHERE MANL = rec.MANL;
    END LOOP;
    COMMIT;
  END;
  
  FUNCTION check_inventory(p_manl NUMBER) RETURN NUMBER IS
    v_tonkho NUMBER;
  BEGIN
    SELECT SOLUONGTON INTO v_tonkho FROM NGUYENLIEU WHERE MANL = p_manl;
    RETURN v_tonkho;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN 0;
  END;
END pkg_nhaphang;
/

PROMPT  Da tao 3 package co ban

PROMPT *** BUOC 4: TAO PROCEDURE VA FUNCTION ***

-- Procedure tao tai khoan
CREATE OR REPLACE PROCEDURE tao_tai_khoan(
  p_username IN VARCHAR2,
  p_manv IN NUMBER,
  p_password IN VARCHAR2,
  p_role_code IN VARCHAR2
) AS
  v_salt RAW(64);
  v_hash RAW(2000);
  v_password_strength VARCHAR2(20);
BEGIN
  -- Kiem tra do manh mat khau
  v_password_strength := pkg_crypto.check_password_strength(p_password);
  IF v_password_strength = 'WEAK' THEN
    RAISE_APPLICATION_ERROR(-20001, 'Mat khau qua yeu. Can it nhat 8 ky tu, chu hoa, chu thuong, so va ky tu dac biet.');
  END IF;
  
  v_salt := pkg_crypto.gen_random_raw(32);
  v_hash := pkg_crypto.hash_password(p_password, v_salt);
  
  INSERT INTO TAIKHOAN(USERNAME, MANV, PASSWORD_HASH, SALT, ROLE_CODE, LOGIN_FAILS, CREATED_AT)
  VALUES (p_username, p_manv, v_hash, v_salt, p_role_code, 0, SYSDATE);
  
  COMMIT;
  
  DBMS_OUTPUT.PUT_LINE('Tao tai khoan thanh cong: ' || p_username || ' - Do manh mat khau: ' || v_password_strength);
END;
/

-- Function dang nhap
CREATE OR REPLACE FUNCTION dang_nhap(
  p_username IN VARCHAR2,
  p_password IN VARCHAR2,
  p_ip IN VARCHAR2
) RETURN VARCHAR2 AS
  PRAGMA AUTONOMOUS_TRANSACTION;
  v_salt RAW(64);
  v_hash RAW(2000);
  v_stored RAW(2000);
  v_locked_until DATE;
  v_fails NUMBER;
  v_role VARCHAR2(30);
  v_manv NUMBER;
  v_password_expired CHAR(1);
BEGIN
  SELECT SALT, PASSWORD_HASH, LOCKED_UNTIL, LOGIN_FAILS, ROLE_CODE, MANV, 
         CASE WHEN PASSWORD_EXPIRES_AT < SYSDATE THEN 'Y' ELSE 'N' END
    INTO v_salt, v_stored, v_locked_until, v_fails, v_role, v_manv, v_password_expired
    FROM TAIKHOAN WHERE USERNAME = p_username;

  IF v_locked_until IS NOT NULL AND v_locked_until > SYSDATE THEN
    INSERT INTO LICHSU_DANGNHAP(USERNAME, MANV, HOATDONG, THOIGIAN, IP_ADDRESS, GHI_CHU)
    VALUES (p_username, v_manv, 'LOGIN_FAIL', SYSDATE, p_ip, 'Tai khoan bi khoa');
    COMMIT;
    RETURN 'LOCKED';
  END IF;
  
  -- Kiem tra password het han
  IF v_password_expired = 'Y' THEN
    INSERT INTO LICHSU_DANGNHAP(USERNAME, MANV, HOATDONG, THOIGIAN, IP_ADDRESS, GHI_CHU)
    VALUES (p_username, v_manv, 'LOGIN_FAIL', SYSDATE, p_ip, 'Mat khau da het han');
    COMMIT;
    RETURN 'EXPIRED';
  END IF;

  v_hash := pkg_crypto.hash_password(p_password, v_salt);

  IF v_hash = v_stored THEN
    UPDATE TAIKHOAN SET LAST_LOGIN_AT = SYSDATE, LOGIN_FAILS = 0, LOCKED_UNTIL = NULL 
    WHERE USERNAME = p_username;
    
    INSERT INTO LICHSU_DANGNHAP(USERNAME, MANV, HOATDONG, THOIGIAN, IP_ADDRESS, GHI_CHU)
    VALUES (p_username, v_manv, 'LOGIN_SUCCESS', SYSDATE, p_ip, 'Dang nhap thanh cong');
    
    COMMIT;
    RETURN 'OK:' || v_role;
  ELSE
    v_fails := v_fails + 1;
    UPDATE TAIKHOAN SET LOGIN_FAILS = v_fails WHERE USERNAME = p_username;
    
    INSERT INTO LICHSU_DANGNHAP(USERNAME, MANV, HOATDONG, THOIGIAN, IP_ADDRESS, GHI_CHU)
    VALUES (p_username, v_manv, 'LOGIN_FAIL', SYSDATE, p_ip, 'Sai mat khau');
    
    IF v_fails >= 5 THEN
      UPDATE TAIKHOAN SET LOCKED_UNTIL = SYSDATE + (15/1440) WHERE USERNAME = p_username;
    END IF;
    
    COMMIT;
    RETURN 'FAIL';
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    COMMIT;
    RETURN 'NOUSER';
END;
/

-- Procedure thay doi mat khau
CREATE OR REPLACE PROCEDURE thay_doi_mat_khau(
  p_username IN VARCHAR2,
  p_old_password IN VARCHAR2,
  p_new_password IN VARCHAR2
) AS
  v_salt RAW(64);
  v_stored_hash RAW(2000);
  v_new_hash RAW(2000);
  v_password_strength VARCHAR2(20);
BEGIN
  -- Lay thong tin hien tai
  SELECT SALT, PASSWORD_HASH INTO v_salt, v_stored_hash
  FROM TAIKHOAN WHERE USERNAME = p_username;
  
  -- Kiem tra mat khau cu
  IF pkg_crypto.hash_password(p_old_password, v_salt) != v_stored_hash THEN
    RAISE_APPLICATION_ERROR(-20002, 'Mat khau cu khong chinh xac');
  END IF;
  
  -- Kiem tra do manh mat khau moi
  v_password_strength := pkg_crypto.check_password_strength(p_new_password);
  IF v_password_strength = 'WEAK' THEN
    RAISE_APPLICATION_ERROR(-20003, 'Mat khau moi qua yeu');
  END IF;
  
  -- Tao salt moi
  v_salt := pkg_crypto.gen_random_raw(32);
  v_new_hash := pkg_crypto.hash_password(p_new_password, v_salt);
  
  -- Cap nhat
  UPDATE TAIKHOAN 
  SET PASSWORD_HASH = v_new_hash,
      SALT = v_salt,
      PASSWORD_CHANGED_AT = SYSDATE,
      PASSWORD_EXPIRES_AT = SYSDATE + 90,
      LOGIN_FAILS = 0,
      LOCKED_UNTIL = NULL
  WHERE USERNAME = p_username;
  
  COMMIT;
  
  DBMS_OUTPUT.PUT_LINE('Doi mat khau thanh cong. Do manh: ' || v_password_strength);
END;
/

-- Cac procedure khac
CREATE OR REPLACE PROCEDURE them_mon(
  p_tenmon VARCHAR2,
  p_loaimon VARCHAR2,
  p_dongia NUMBER,
  p_mamon OUT NUMBER
) AS
BEGIN
  p_mamon := seq_mon.NEXTVAL;
  INSERT INTO MON(MAMON, TENMON, LOAIMON, DONGIA, TRANGTHAI)
  VALUES (p_mamon, p_tenmon, p_loaimon, p_dongia, 'BAN');
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE them_nhanvien(
  p_hoten VARCHAR2,
  p_email VARCHAR2,
  p_sodt VARCHAR2,
  p_ngaysinh DATE
) AS
  v_manv NUMBER;
BEGIN
  v_manv := seq_nhanvien.NEXTVAL;
  INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, SODT, NGAYSINH, TRANGTHAI, NGAYTAO)
  VALUES (v_manv, p_hoten, p_email, p_sodt, p_ngaysinh, 'ACTIVE', SYSDATE);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE them_ban(
  p_tenban VARCHAR2,
  p_vitri VARCHAR2
) AS
  v_maban NUMBER;
BEGIN
  v_maban := seq_ban.NEXTVAL;
  INSERT INTO BAN(MABAN, TENBAN, VITRI, TRANGTHAI)
  VALUES (v_maban, p_tenban, p_vitri, 'TRONG');
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE them_khachhang(
  p_hoten VARCHAR2,
  p_sodt VARCHAR2,
  p_email VARCHAR2,
  p_loaikh VARCHAR2 DEFAULT 'LE'
) AS
  v_makh NUMBER;
BEGIN
  v_makh := seq_khachhang.NEXTVAL;
  INSERT INTO KHACHHANG(MAKH, HOTEN, SODT, EMAIL, LOAIKH)
  VALUES (v_makh, p_hoten, p_sodt, p_email, p_loaikh);
  COMMIT;
END;
/

PROMPT  Da tao 8 procedure/function

PROMPT *** BUOC 5: TAO VIEW ***

-- View doanh thu theo ngay
CREATE OR REPLACE VIEW v_doanhthu_ngay AS
SELECT 
  TRUNC(NGAYLAP) AS NGAY,
  COUNT(*) AS SO_HOA_DON,
  SUM(TONGTIEN) AS DOANH_THU,
  ROUND(AVG(TONGTIEN), 2) AS TRUNG_BINH_HD
FROM HOADON
WHERE TRANGTHAI = 'DA_THANH_TOAN'
GROUP BY TRUNC(NGAYLAP)
ORDER BY NGAY DESC;
/

-- View mon ban chay
CREATE OR REPLACE VIEW v_mon_ban_chay AS
SELECT 
  m.MAMON,
  m.TENMON,
  m.LOAIMON,
  COUNT(ct.MAHD) AS SO_LAN_BAN,
  SUM(ct.SOLUONG) AS TONG_SO_LUONG,
  SUM(ct.THANHTIEN) AS TONG_DOANH_THU,
  ROUND(AVG(ct.DONGIA), 2) AS GIA_TRUNG_BINH
FROM MON m
JOIN CHITIET_HD ct ON m.MAMON = ct.MAMON
JOIN HOADON h ON ct.MAHD = h.MAHD
WHERE h.TRANGTHAI = 'DA_THANH_TOAN'
GROUP BY m.MAMON, m.TENMON, m.LOAIMON
ORDER BY TONG_DOANH_THU DESC;
/

-- View hoa don cua nhan vien
CREATE OR REPLACE VIEW v_hoadon_nhanvien AS
SELECT h.MAHD, h.MANV, h.MABAN, h.MAKH, h.NGAYLAP, h.TONGTIEN, h.TRANGTHAI,
       nv.HOTEN AS TEN_NHANVIEN,
       b.TENBAN,
       kh.HOTEN AS TEN_KHACHHANG,
       kh.LOAIKH
FROM HOADON h
JOIN NHANVIEN nv ON h.MANV = nv.MANV
JOIN BAN b ON h.MABAN = b.MABAN
LEFT JOIN KHACHHANG kh ON h.MAKH = kh.MAKH
ORDER BY h.NGAYLAP DESC;
/

-- View chi tiet hoa don
CREATE OR REPLACE VIEW v_chitiet_hoadon AS
SELECT 
  ct.MAHD,
  ct.MAMON,
  m.TENMON,
  m.LOAIMON,
  ct.SOLUONG,
  ct.DONGIA,
  ct.GIAMGIA,
  ct.THANHTIEN,
  h.NGAYLAP,
  h.MANV,
  h.TRANGTHAI
FROM CHITIET_HD ct
JOIN MON m ON ct.MAMON = m.MAMON
JOIN HOADON h ON ct.MAHD = h.MAHD
ORDER BY h.NGAYLAP DESC, ct.MAHD;
/

-- View ton kho
CREATE OR REPLACE VIEW v_tonkho AS
SELECT 
  nl.MANL,
  nl.TENNL,
  nl.DONVI,
  nl.SOLUONGTON,
  ncc.TENNCC,
  nl.SECURITY_LEVEL,
  CASE 
    WHEN nl.SOLUONGTON < 10 THEN 'SAP_HET'
    WHEN nl.SOLUONGTON < 30 THEN 'CAN_NHAP'
    ELSE 'DU'
  END AS TINH_TRANG
FROM NGUYENLIEU nl
LEFT JOIN NHACUNGCAP ncc ON nl.MANCC_CHINH = ncc.MANCC
ORDER BY nl.SOLUONGTON;
/

-- View bao cao bao mat (M?I)
CREATE OR REPLACE VIEW v_bao_cao_bao_mat AS
SELECT 
  'TAI_KHOAN' AS LOAI,
  COUNT(*) AS SO_LUONG,
  TO_CHAR(MAX(LAST_LOGIN_AT), 'YYYY-MM-DD') AS NGAY_DANG_NHAP_CUOI,
  SUM(CASE WHEN LOCKED_UNTIL IS NOT NULL THEN 1 ELSE 0 END) AS BI_KHOA
FROM TAIKHOAN
UNION ALL
SELECT 
  'AUDIT_LOG',
  COUNT(*),
  TO_CHAR(MAX(ACTION_TIME), 'YYYY-MM-DD'),
  0
FROM AUDIT_LOG
UNION ALL
SELECT 
  'FGA_LOG',
  COUNT(*),
  TO_CHAR(MAX(TIMESTAMP), 'YYYY-MM-DD'),
  0
FROM FGA_LOG;
/

PROMPT  Da tao 6 view co ban

PROMPT *** BUOC 6: THEM DU LIEU MAU ***

-- Them phan quyen
INSERT INTO PHANQUYEN VALUES('ADMIN','Quan tri he thong');
INSERT INTO PHANQUYEN VALUES('QUANLY','Quan ly cua hang');
INSERT INTO PHANQUYEN VALUES('NHANVIEN','Nhan vien phuc vu');
INSERT INTO PHANQUYEN VALUES('THUKHO','Nhan vien thu kho');
COMMIT;

-- Them nhan vien
INSERT INTO NHANVIEN VALUES(1,'Nguyen Van Admin','admin@cafe.com','0901234567',TO_DATE('1990-01-01','YYYY-MM-DD'),'ACTIVE',SYSDATE);
INSERT INTO NHANVIEN VALUES(2,'Tran Thi Quan Ly','quanly@cafe.com','0907654321',TO_DATE('1985-05-15','YYYY-MM-DD'),'ACTIVE',SYSDATE);
INSERT INTO NHANVIEN VALUES(3,'Le Van Phuc Vu','phucvu@cafe.com','0909876543',TO_DATE('1998-03-20','YYYY-MM-DD'),'ACTIVE',SYSDATE);
INSERT INTO NHANVIEN VALUES(4,'Pham Thi Thu Kho','thukho@cafe.com','0901122334',TO_DATE('1992-07-10','YYYY-MM-DD'),'ACTIVE',SYSDATE);
COMMIT;

-- Tao tai khoan
BEGIN
  tao_tai_khoan('admin', 1, 'Admin@123', 'ADMIN');
  tao_tai_khoan('quanly', 2, 'Quanly@123', 'QUANLY');
  tao_tai_khoan('phucvu', 3, 'Phucvu@123', 'NHANVIEN');
  tao_tai_khoan('thukho', 4, 'Thukho@123', 'THUKHO');
  DBMS_OUTPUT.PUT_LINE(' Da tao 4 tai khoan thanh cong!');
END;
/

-- Them ban
INSERT INTO BAN VALUES(1,'Ban 1','Tang 1 - Gan cua so','TRONG');
INSERT INTO BAN VALUES(2,'Ban 2','Tang 1 - Gan quay','TRONG');
INSERT INTO BAN VALUES(3,'Ban 3','Tang 1 - Trung tam','TRONG');
INSERT INTO BAN VALUES(4,'Ban 4','Tang 2 - Phong rieng','TRONG');
INSERT INTO BAN VALUES(5,'Ban 5','Tang 2 - Ban dai','TRONG');
INSERT INTO BAN VALUES(6,'Ban VIP 1','Tang 3 - View tot','TRONG');
INSERT INTO BAN VALUES(7,'Ban VIP 2','Tang 3 - Khong gian rieng','TRONG');
INSERT INTO BAN VALUES(8,'Ban Bao Tri','Kho','BAO_TRI');
COMMIT;

-- Them khach hang
INSERT INTO KHACHHANG VALUES(1001,'Khach le',NULL,NULL,'LE');
INSERT INTO KHACHHANG VALUES(1002,'Nguyen Van A','0912345678','vana@email.com','THUONG');
INSERT INTO KHACHHANG VALUES(1003,'Tran Thi B','0923456789','thib@email.com','VIP');
INSERT INTO KHACHHANG VALUES(1004,'Le Van C','0934567890','lec@email.com','THUONG');
INSERT INTO KHACHHANG VALUES(1005,'Pham Thi D','0945678901','phamd@email.com','VIP');
COMMIT;

-- Them mon
INSERT INTO MON VALUES(1,'Ca phe sua','Ca phe',25000,'BAN');
INSERT INTO MON VALUES(2,'Ca phe den','Ca phe',20000,'BAN');
INSERT INTO MON VALUES(3,'Bac xiu','Ca phe',28000,'BAN');
INSERT INTO MON VALUES(4,'Cappuccino','Ca phe',35000,'BAN');
INSERT INTO MON VALUES(5,'Tra sua tran chau','Tra sua',30000,'BAN');
INSERT INTO MON VALUES(6,'Tra sua matcha','Tra sua',32000,'BAN');
INSERT INTO MON VALUES(7,'Tra dao','Tra',25000,'BAN');
INSERT INTO MON VALUES(8,'Tra vai','Tra',25000,'BAN');
INSERT INTO MON VALUES(9,'Nuoc cam','Nuoc ep',35000,'BAN');
INSERT INTO MON VALUES(10,'Sinh to bo','Sinh to',40000,'BAN');
INSERT INTO MON VALUES(11,'Banh mi','Do an',20000,'BAN');
INSERT INTO MON VALUES(12,'Banh ngot','Do an',25000,'BAN');
INSERT INTO MON VALUES(13,'My y','Do an',45000,'BAN');
INSERT INTO MON VALUES(14,'Com chien','Do an',35000,'BAN');
COMMIT;

-- Them nha cung cap
INSERT INTO NHACUNGCAP VALUES(1,'Cong ty Ca phe Viet','0281234567','caphe@supplier.com','123 Nguyen Van Cu, Q1, TP.HCM');
INSERT INTO NHACUNGCAP VALUES(2,'Cong ty Tra Sua ABC','0287654321','trasua@supplier.com','456 Le Loi, Q3, TP.HCM');
INSERT INTO NHACUNGCAP VALUES(3,'Cong ty Thuc pham XYZ','0283456789','thucpham@supplier.com','789 Hai Ba Trung, Q1, TP.HCM');
INSERT INTO NHACUNGCAP VALUES(4,'Cong ty Nuoc giai khat','0289998888','nuoc@supplier.com','321 Vo Thi Sau, Q3, TP.HCM');
COMMIT;

-- Them nguyen lieu
INSERT INTO NGUYENLIEU VALUES(1,'Ca phe hat Robusta','kg',50,'PUBLIC',1);
INSERT INTO NGUYENLIEU VALUES(2,'Ca phe hat Arabica','kg',30,'PUBLIC',1);
INSERT INTO NGUYENLIEU VALUES(3,'Sua tuoi','lit',80,'INTERNAL',3);
INSERT INTO NGUYENLIEU VALUES(4,'Duong','kg',100,'PUBLIC',1);
INSERT INTO NGUYENLIEU VALUES(5,'Tra xanh','kg',20,'PUBLIC',2);
INSERT INTO NGUYENLIEU VALUES(6,'Tran chau','kg',15,'PUBLIC',2);
INSERT INTO NGUYENLIEU VALUES(7,'Bot matcha','kg',10,'INTERNAL',2);
INSERT INTO NGUYENLIEU VALUES(8,'Cam tuoi','kg',40,'PUBLIC',3);
INSERT INTO NGUYENLIEU VALUES(9,'Thit bo','kg',25,'CONFIDENTIAL',3);
INSERT INTO NGUYENLIEU VALUES(10,'Gao','kg',200,'PUBLIC',3);
INSERT INTO NGUYENLIEU VALUES(11,'Bot mi','kg',60,'PUBLIC',3);
COMMIT;

-- Tao khoa AES
INSERT INTO APP_CONFIG VALUES('AES_KEY', SYS.DBMS_CRYPTO.RANDOMBYTES(32));
INSERT INTO APP_CONFIG VALUES('SESSION_TIMEOUT', UTL_RAW.CAST_TO_RAW('30'));
INSERT INTO APP_CONFIG VALUES('MAX_LOGIN_ATTEMPTS', UTL_RAW.CAST_TO_RAW('5'));
COMMIT;

PROMPT  Da them du lieu mau

PROMPT ========================================
PROMPT HOAN THANH FILE 2: SETUP CORE!
PROMPT 
PROMPT TIEP THEO:
PROMPT Chay file 02_SETUP_ADVANCED.sql
PROMPT ========================================

-- Kiem tra tong quan
SELECT 'Tables' as Type, COUNT(*) as Count FROM user_tables
UNION ALL
SELECT 'Views', COUNT(*) FROM user_views
UNION ALL
SELECT 'Procedures', COUNT(*) FROM user_procedures
UNION ALL
SELECT 'Packages', COUNT(*) FROM user_objects WHERE object_type = 'PACKAGE'
UNION ALL
SELECT 'Sequences', COUNT(*) FROM user_sequences;